language: java
jdk:
  - openjdk8

before_install:
    - wget https://github.com/giuseppeamato/lsc-scim-plugin/releases/download/v1.1.0/wso2ids.crt
    - sudo keytool -importcert -trustcacerts -noprompt -alias wso2ids -file wso2ids.crt -storepass changeit -keystore $JAVA_HOME/lib/security/cacerts

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)