language: java
before_install:
    - find / -name cacerts
    - wget https://github.com/giuseppeamato/lsc-scim-plugin/releases/download/v1.1.0/wso2ids.crt
    - keytool -importcert -trustcacerts -noprompt -alias wso2ids -file wso2ids.crt -storepass changeit -keystore $JAVA_HOME/jre/lib/security/cacerts
